name: Build and push image JAVA

on:
  workflow_dispatch: {}

jobs:

  build-and-push:
    name: Build and push JAVA
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Build and validate
        run: |
          echo "docker build"
          docker build -t mi-app:1.0.0 .
                  
